### ISSUE TITLE
Why pass connect exception?

### ISSUE THREAD

**Issue by BakasuraRCE** [jaraco/irc#145]
I currently have this error "ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)" when I connect too fast to a server too many times, which is normal, what I do not understand is because the following line is allowing the bot to follow the normal course?

https://github.com/jaraco/irc/blob/f2df157db5a2f89fec7c7399462030097f4e6dc4/irc/bot.py#L188-L189

**Comment by jaraco** [comment]
I don't know. That does seem like bad form, especially since there's no justification there.

**Comment by BakasuraRCE** [comment]
One solution may be to eliminate the try except, to allow the execption to go up to higher terms.

Could something go wrong by letting the exception run its course?

Could you confirm it?

**Comment by jaraco** [comment]
As I read the code a bit more, I see that the bot is programmed to repeatedly reconnect, following the `recon` strategy. If the exception were allowed to pass, it would crash the server rather than follow the reconnection strategy. Perhaps the exception should be trapped in jump_server or in another part of the logic.

There may be a better way to handle this intention, but I'm fairly certain removing that exception trap will cause issues.
