### ISSUE TITLE
How to use data from one event handler in a different one?

### ISSUE THREAD

**Issue by ahopelesshadow** [jaraco/irc#227]
I'm not sure if this is an issue as much of a question, its entirely possible I'm doing something wrong.

But lets say i write an event handler on_privmsg with 

```
if event.arguments[0] == ".whois":
    whois = server.whois(event.arguments[1])
    userip = server.send_items("USERIP", event.arguments[1])
    server.privmsg(event.target, f"{whois} {userip}")
```

the issue here is while inside of that function, my event handlers for on_whois and on_iplookup do not fire, as the bot can only receive one response at a time.  I wrote and defined the proper functions to parse out both whois and userip, and they both work, if i f10 through the entire program, but the problem there is my on_privmsg event has ended at that point...  so when i go to reply with the variables in the fstring, they show as none...

So I guess my question is how can i get the data from those other two functions back into my privmsg function as the events wernt caught yet?

I did see another issue relating to whois, and the reply was to create a handler to catch and parse out the reply.  I have done that and it works, but i cant seem to figure out how to use the data from that function.

**Comment by jaraco** [comment]
I'm not sure what `server` is in this context. Are you using `def on_privmsg(self, server, event)`? Or maybe `def on_prvmsg(server, conn, event)`?

I see now. `server` appears to be a `irc.client.ServerConnection`. And you're right, you can't simply assign the results of a `server.whois` or `server.send_items` because those methods don't return anything. All they do is send messages off to the IRC server.

And that's how IRC servers work - they just send messages around. They don't have a function calling interface.

So when you're calling `server.whois()`, you're saying, please at some point send me a message about "who is" this entity.

And you're right, if you set up some handlers to receive these responses, your bot may be able to associate the responses. You'll need to manage this state in client, however. For example, you could create an object `class WhoisRequest(SimpleNamespace)` and save it in memory, something like:

```
self.current_whois_request = WhoisRequest(name=event.arguments[1], target=event.target)
```

And then in `on_whois` (or similar):

```
self.current_whois_request.whois = event.arguments[1]
self.handle_whois()
```

And in `on_userip`:

```
self.current_whois_request.userip = event.arguments[1]
self.handle_whois()
```

Then in handle_whois(), check if the request is fulfilled and respond accordingly:

```
def handle_whois(self):
    if not hasattr(self.current_whois_request, 'whois') or not hasattr(self.current_whois_request, 'userip'):
        # request isn't complete yet; do nothing
        return
    server.privmsg(current_whois_request.target, f"{self.current_whois_request.whois} {self.current_whois_request.userip}")
    self.current_whois_request = None
```

The problem is that you don't have any way to know (if and when the server responds) that the response is relevant to this `event.arguments[1]` or a different one, so you could get race conditions where multiple requests come in and overlap. Depending on how much of a risk that concern is for what you're trying to accomplish, you might need to build in some logic around maintaining queues of these requests.

I hope that helps. Let us know how it goes.

**Comment by jaraco** [comment]
Note that in my prior example, I suggested storing the intermediate state on the Bot or IRC Client object, but of course you can store the state wherever you like, in a global variable, in a database, etc. You'll need to figure out what's right for your application.

**Comment by ahopelesshadow** [comment]
> Note that in my prior example, I suggested storing the intermediate state on the Bot or IRC Client object, but of course you can store the state wherever you like, in a global variable, in a database, etc. You'll need to figure out what's right for your application.

Thanks for both of your replies, unfortunately I could not find a suitable way to make this work at all.  All of the functions can be written and i can interact with the responses from the server, but since the data can't reliably be pulled into a different function at the same time, I sorta gave up on it.  What I did to use these two specific features of irc, was pull them from the server i was interacting with via xml_rpc built into anope.  Further more I am testing the m_json module for anope since that includes authentication.  We can probably close this issue unless you want to leave it for other replies to see if someone comes up with a better solution.  But I was unable to find something that would work in the bot I was building.
